version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"

  hazelcast:
    image: hazelcast/hazelcast:5.3
    container_name: hazelcast-server
    ports:
      - "5701:5701"
    environment:
      - JAVA_OPTS=-Dhazelcast.local.publicAddress=127.0.0.1
